repos:
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: "0.4.0" # the revision or tag to clone at
    hooks:
      - id: sync_with_poetry
        args: [] # optional args
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      -   id: end-of-file-fixer
          exclude: nibiru/proto/.+

      -   id: trailing-whitespace
          exclude: nibiru/proto/.+

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        files: \.py$
        exclude: nibiru/proto/.+

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: \.py$
        exclude: nibiru/proto/.+
        args: [ "--profile", "black" ]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
