[tool.poetry]
# --------------------------------------- required fields
name = "nibiru"
version = "0.0.17"
# packages: A list of packages to include in the final distribution. The 'name'
#   specifies the PyPI project name, wherase 'packages' specifies what a user
#   will import in a Python module.
packages = [
  { include = "nibiru" },
]
# --------------------------------------- optional fields
description = "Python SDK for interacting with Nibiru."
authors = ["Nibiru Chain (dev@nibiru.fi)"]
maintainers = ["@matthiasmat", "Unique-Divine", "@NibiruHeisenberg"]
license = "MIT"
readme = "README.md" # similar to long_description in setuptools
repository = "https://github.com/NibiruChain/py-sdk"
documentation = "https://nibiru-py.readthedocs.io/"
keywords = ["nibiru", "blockchain", "sdk", "python", "cosmos"]
classifiers = [
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Intended Audience :: Developers"
]

[tool.poetry.dependencies]
python = "^3.9"
grpcio = "^1.48.0"
asyncio = "^3.4.3"
bech32 = "^1.2.0"
python-dotenv = "^0.20.0"
protobuf = "3.20.1" # see README
requests = "^2.28.1"
aiohttp = "^3.8.1"
ecdsa = "^0.18.0"
mnemonic = "^0.20"
hdwallets = "^0.1.2"
pysha3 = "^1.0.2"
bip32 = "^3.1"
eip712-structs = "^1.1.0"
coincurve = "^17.0.0"
aiocron = "^1.8"
pytest = "^7.1.2"
pre-commit = "^2.20.0"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
flake8 = "^5.0.4"

[tool.black]
line-length = 88
skip-string-normalization = true
include = '.*\.pyi?$'
target-version = ['py39']
extend-exclude = '''
^/(
    \.vscode
  | nibiru/proto
)$
'''

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
