name: Linting
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.13"

      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "W503,E501,F811,F541,W605,E203,F405,E722,W191,F403,F821,E101,N806,N802,N801,N811,N818"
          exclude: "nibiru/proto/*"
          max-line-length: "88"
