name: Linting
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.12"

      # Install pipenv
      - name: Install flake
        run: |
          python -m pip install flake8==4.0.1

      # Run lint tests
      - name: Run linter for changed files.
        id: run-lint
        run: |
          flake8 $(git status -s | grep -E '\.py$' | cut -c 4-)
